In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns     

In [2]:
movies_data = pd.read_csv('movies.csv')
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [3]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

# Data Preprocessing

In [4]:
pip install -U gensim

Note: you may need to restart the kernel to use updated packages.


In [5]:
# feature selection
movies_data['content']= movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['title']+' '+movies_data['cast']+' '+movies_data['director']
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ...  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   
3  Following the death of District Attorney Harve...  112.312950  ...   
4  John Carter is a war-weary, former military ca...   43.926995  ...   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average vote_count  \
0                                    Avatar           7.2      11800   
1  Pirates of the Caribbean: At World's End           6.9       4500   
2                                   Spectre           6.3       4466   
3                     The Dark Knight Rises           7.6       9106   
4                               John Carter           6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  \
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron   
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski   
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes   
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan   
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton   

                                             content  
0  Action Adventure Fantasy Science Fiction cultu...  
1  Adventure Fantasy Action ocean drug abus

In [6]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
content                 1046
dtype: int64

In [7]:
movies_data['content'].fillna(' ',inplace=True)

In [8]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
content                    0
dtype: int64

**(i)Stemming using stopwords**

In [9]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [10]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\monda\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:
# make corpus after removing symbols and numbers, tokenization , lower all alphabets and lemmatization 

from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

corpus=[]
for i in range(0,len(movies_data)):
    review=re.sub('[^a-zA-Z]',' ',movies_data['content'][i]) # make review sentence with the charecters having a-z or A-Z latter  
    review=review.lower() # make every charecter lower case
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [12]:
corpus

['action adventure fantasy science fiction culture clash future space war space colony society enter world pandora avatar sam worthington zoe saldana sigourney weaver stephen lang michelle rodriguez james cameron',
 'adventure fantasy action ocean drug abuse exotic island east india trading company love one life end world adventure begin pirate caribbean world end johnny depp orlando bloom keira knightley stellan skarsg u e rd chow yun fat gore verbinski',
 'action adventure crime spy based novel secret agent sequel mi plan one escape spectre daniel craig christoph waltz l u e seydoux ralph fiennes monica bellucci sam mendes',
 'action crime drama thriller dc comic crime fighter terrorist secret identity burglar legend end dark knight rise christian bale michael caine gary oldman anne hathaway tom hardy christopher nolan',
 'action adventure science fiction based novel mar medallion space travel princess lost world found another john carter taylor kitsch lynn collins samantha morton wi

**(ii)TF-IDF model to get sentence to vector**

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(ngram_range=(1,3),
                  max_features=4)

In [14]:
X=cv.fit_transform(corpus)
cv.vocabulary_ 

{'action': 0, 'drama': 2, 'thriller': 3, 'comedy': 1}

In [15]:
corpus[0]

'action adventure fantasy science fiction culture clash future space war space colony society enter world pandora avatar sam worthington zoe saldana sigourney weaver stephen lang michelle rodriguez james cameron'

In [16]:
X[0].toarray()

array([[1., 0., 0., 0.]])

In [17]:
X=X.toarray()
X

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
X.shape

(4803, 4)

In [19]:
movies_data.shape

(4803, 25)

# Generate Similarity Index

In [20]:
#using Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(X)
print(similarity)

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
similarity.shape

(4803, 4803)

### Making recommandation using steps 

In [22]:
# taking input which movie user want to watch
wanted_movie = input('Movie you want : ')

Movie you want : Avengers:Endgame


In [23]:
# list of movie names 
l1=list(movies_data['title'])

In [24]:
# choose some closest possible movies name as per the user given input
import difflib    # this library will try to detect something similarities if the movie spelling is wrong or the movie name does not exist
closest_possible_movies = difflib.get_close_matches(wanted_movie,l1)
closest_possible_movies

['Highlander: Endgame']

In [25]:
# closest movies name as per the user given input 
closest_movie = closest_possible_movies[0]
closest_movie

'Highlander: Endgame'

In [26]:
# index of the closest movie
index= movies_data[movies_data.title == closest_movie]['index'].values[0]  #values[0] will try to store the index value into the similarity score list 
index

2592

In [27]:
# calculate the similarity score of other movies with my closest movies
similarity_score = list(enumerate(similarity[index]))
similarity_score

[(0, 1.0),
 (1, 1.0),
 (2, 1.0),
 (3, 0.6261976318855494),
 (4, 1.0),
 (5, 1.0),
 (6, 0.0),
 (7, 1.0),
 (8, 0.0),
 (9, 1.0),
 (10, 0.0),
 (11, 0.7195037681880533),
 (12, 1.0),
 (13, 1.0),
 (14, 1.0),
 (15, 0.0),
 (16, 1.0),
 (17, 1.0),
 (18, 0.7522488277291752),
 (19, 1.0),
 (20, 1.0),
 (21, 1.0),
 (22, 0.0),
 (23, 0.0),
 (24, 0.7860277414792901),
 (25, 0.0),
 (26, 1.0),
 (27, 0.7195037681880533),
 (28, 0.7195037681880533),
 (29, 0.7195037681880533),
 (30, 1.0),
 (31, 1.0),
 (32, 0.0),
 (33, 0.7195037681880533),
 (34, 0.0),
 (35, 1.0),
 (36, 1.0),
 (37, 0.0),
 (38, 1.0),
 (39, 1.0),
 (40, 0.0),
 (41, 0.7195037681880533),
 (42, 0.0),
 (43, 0.7195037681880533),
 (44, 1.0),
 (45, 0.6261976318855494),
 (46, 1.0),
 (47, 1.0),
 (48, 1.0),
 (49, 0.0),
 (50, 1.0),
 (51, 1.0),
 (52, 1.0),
 (53, 1.0),
 (54, 0.0),
 (55, 0.7522488277291752),
 (56, 0.0),
 (57, 0.0),
 (58, 0.6087115609484695),
 (59, 1.0),
 (60, 0.0),
 (61, 1.0),
 (62, 1.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.6261976318855494),
 (66, 0.

In [28]:
#sort similar movies according to similarity score
similar_movies = sorted(similarity_score,key = lambda x:x[1], reverse = True) 
similar_movies

[(0, 1.0),
 (1, 1.0),
 (2, 1.0),
 (4, 1.0),
 (5, 1.0),
 (7, 1.0),
 (9, 1.0),
 (12, 1.0),
 (13, 1.0),
 (14, 1.0),
 (16, 1.0),
 (17, 1.0),
 (19, 1.0),
 (20, 1.0),
 (21, 1.0),
 (26, 1.0),
 (30, 1.0),
 (31, 1.0),
 (35, 1.0),
 (36, 1.0),
 (38, 1.0),
 (39, 1.0),
 (44, 1.0),
 (46, 1.0),
 (47, 1.0),
 (48, 1.0),
 (50, 1.0),
 (51, 1.0),
 (52, 1.0),
 (53, 1.0),
 (59, 1.0),
 (61, 1.0),
 (62, 1.0),
 (68, 1.0),
 (72, 1.0),
 (74, 1.0),
 (75, 1.0),
 (79, 1.0),
 (81, 1.0),
 (85, 1.0),
 (91, 1.0),
 (94, 1.0),
 (98, 1.0),
 (101, 1.0),
 (102, 1.0),
 (107, 1.0),
 (111, 1.0),
 (115, 1.0),
 (126, 1.0),
 (129, 1.0),
 (138, 1.0),
 (151, 1.0),
 (158, 1.0),
 (159, 1.0),
 (162, 1.0),
 (163, 1.0),
 (168, 1.0),
 (169, 1.0),
 (174, 1.0),
 (182, 1.0),
 (183, 1.0),
 (187, 1.0),
 (193, 1.0),
 (199, 1.0),
 (205, 1.0),
 (206, 1.0),
 (207, 1.0),
 (208, 1.0),
 (210, 1.0),
 (223, 1.0),
 (224, 1.0),
 (225, 1.0),
 (228, 1.0),
 (229, 1.0),
 (230, 1.0),
 (232, 1.0),
 (233, 1.0),
 (242, 1.0),
 (253, 1.0),
 (260, 1.0),
 (262, 1.0

In [29]:
print('0','.',movies_data.title[index])
for i in range(1,20):
    index = similar_movies[i][0]
    print(i,'.',movies_data.title[index])

0 . Highlander: Endgame
1 . Pirates of the Caribbean: At World's End
2 . Spectre
3 . John Carter
4 . Spider-Man 3
5 . Avengers: Age of Ultron
6 . Batman v Superman: Dawn of Justice
7 . Pirates of the Caribbean: Dead Man's Chest
8 . The Lone Ranger
9 . Man of Steel
10 . The Avengers
11 . Pirates of the Caribbean: On Stranger Tides
12 . The Hobbit: The Battle of the Five Armies
13 . The Amazing Spider-Man
14 . Robin Hood
15 . Captain America: Civil War
16 . Spider-Man 2
17 . Iron Man 3
18 . Transformers: Revenge of the Fallen
19 . Transformers: Age of Extinction


# Movie Recommendation system

In [30]:
wanted_movie = input('Movie you want : ') 
l1=list(movies_data['title'])
import difflib
closest_possible_movies = difflib.get_close_matches(wanted_movie,l1)
closest_movie = closest_possible_movies[0]
index= movies_data[movies_data.title == closest_movie]['index'].values[0]
similarity_score = list(enumerate(similarity[index]))
similar_movies = sorted(similarity_score,key = lambda x:x[1], reverse = True)

print('0','.',movies_data.title[index])
for i in range(1,20):
    index = similar_movies[i][0]
    print(i,'.',movies_data.title[index])

Movie you want : Birbie
0 . Buried
1 . The Curious Case of Benjamin Button
2 . The Wolfman
3 . The Revenant
4 . Gravity
5 . The Taking of Pelham 1 2 3
6 . The Spanish Prisoner
7 . Transcendence
8 . What Lies Beneath
9 . The Departed
10 . The Girl with the Dragon Tattoo
11 . Valkyrie
12 . The Devil's Own
13 . K-19: The Widowmaker
14 . Zodiac
15 . Shutter Island
16 . Road to Perdition
17 . The Day the Earth Stood Still
18 . The Manchurian Candidate
19 . Thirteen Days
